### PR TITLE
typo #3

### PR DESCRIPTION
**Pull request by AlanSwenson**

### CODE REVIEW

**Comment by kstolte** [comment]
can you make the change in the `patch-2` branch of your fork? this way the commit will be added to your previous pull request, #8.

**Comment by AlanSwenson** [comment]
lol, i swear ill figure it out sooner or later.

**Comment by kstolte** [comment]
The reason why I would prefer it in the previous pull request is that the changes are related. Ideally, you want to keep like changes in the same pull request. Makes it easier to track and reduces the number of merges to keep the git log cleaner.

**Comment by kstolte** [comment]
@AlanSwenson you fine you're just getting started

**Comment by kstolte** [comment]
Closing as changes were made to @AlanSwenson 's `patch-2` branch instead

**Pull request closed without merging**
