### PR TITLE
typo

### PR DESCRIPTION
**Pull request by AlanSwenson**

### CODE REVIEW

**Comment by kstolte** [comment]
the file i believe is located here `src/app/app.component.ts`

**Comment by kstolte** [comment]
Closing as #8 is the appropriate branch.

**Comment by AlanSwenson** [comment]
Done, still practicing my github etiquette

**Comment by kstolte** [comment]
I'm going to pull this one to prevent needing to rebuild this site.

**Comment by AlanSwenson** [comment]
Do i just delete my branch now?

**Comment by kstolte** [comment]
Yep, you can do that now since your changes have been merged.

**Pull request merged**
